# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 4d37b06
_src_path: https://github.com/gotofritz/copier-python-template
author_email: gotofritz@users.noreply.github.com
author_name: gotofritz
cli: true
org_name: gotofritz
package_name: claude_code_example
project_description: A simple ANKI based project to get used to working with Claude
    Code
project_name: claude-code-example
project_url: https://github.com/gotofritz/claude-code-example
python_version: '3.13'
with_conventional_commits: true
